# -*- coding: utf-8 -*-
"""HydrogenEfficiencyDashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11yLmjCE566QpXWEV4m0Y_tlUmw6qVrcL
"""

import streamlit as st
import openrouteservice
import geopandas as gpd
import matplotlib.pyplot as plt
from shapely.geometry import LineString, Point
import pandas as pd
import numpy as np
import requests
import time
import folium
import branca.colormap as cm
from streamlit_folium import folium_static

# Page configuration
st.set_page_config(
    page_title="Hydrogen Route Efficiency Analyzer",
    page_icon="🚗",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Custom CSS for better styling
st.markdown("""
<style>
    .main-header {
        font-size: 2.5rem;
        color: #1f77b4;
        text-align: center;
        margin-bottom: 2rem;
    }
    .metric-card {
        background-color: #f0f2f6;
        padding: 1rem;
        border-radius: 10px;
        border-left: 4px solid #1f77b4;
        margin: 0.5rem 0;
    }
    .route-comparison {
        background-color: white;
        padding: 1rem;
        border-radius: 10px;
        box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        margin: 1rem 0;
    }
    .secret-status {
        padding: 0.5rem;
        border-radius: 5px;
        margin: 0.5rem 0;
    }
    .secret-ok {
        background-color: #d4edda;
        border: 1px solid #c3e6cb;
        color: #155724;
    }
    .secret-missing {
        background-color: #f8d7da;
        border: 1px solid #f5c6cb;
        color: #721c24;
    }
</style>
""", unsafe_allow_html=True)

# Title and description
st.markdown('<h1 class="main-header">🚗 Hydrogen Route Efficiency Analyzer</h1>', unsafe_allow_html=True)

st.markdown("""
This dashboard analyzes multiple driving routes with a focus on hydrogen fuel efficiency.
It calculates energy consumption based on both distance and elevation changes.
""")

# API Key management
def get_api_key():
    """Get API key from secrets or user input with fallback"""
    # First try to get from secrets
    try:
        if hasattr(st, 'secrets') and 'OPENROUTE_API_KEY' in st.secrets:
            return st.secrets['OPENROUTE_API_KEY']
    except Exception:
        pass

    # Fallback to environment variable
    env_key = os.getenv('OPENROUTE_API_KEY')
    if env_key:
        return env_key

    # Final fallback - user input
    return None

# Check API key status
api_key = get_api_key()

# Sidebar for user inputs
st.sidebar.header("🔑 API Configuration")

if api_key:
    st.sidebar.markdown(f'<div class="secret-status secret-ok">✅ API Key loaded from secrets</div>', unsafe_allow_html=True)
    st.sidebar.info("API key is securely loaded from environment secrets")
else:
    st.sidebar.markdown(f'<div class="secret-status secret-missing">⚠️ No API key in secrets</div>', unsafe_allow_html=True)
    api_key = st.sidebar.text_input(
        "Enter OpenRouteService API Key",
        type="password",
        help="Get your free API key from https://openrouteservice.org/"
    )

st.sidebar.header("📍 Route Configuration")

# Default coordinates (Oakland to San Jose)
col1, col2 = st.sidebar.columns(2)

with col1:
    st.subheader("Start Point")
    start_lat = st.number_input("Start Latitude", value=37.8044, format="%.6f")
    start_lon = st.number_input("Start Longitude", value=-122.2711, format="%.6f")

with col2:
    st.subheader("End Point")
    end_lat = st.number_input("End Latitude", value=37.3382, format="%.6f")
    end_lon = st.number_input("End Longitude", value=-121.8863, format="%.6f")

# Waypoints for alternative routes
st.sidebar.subheader("🔄 Alternative Route Waypoints")

col3, col4 = st.sidebar.columns(2)

with col3:
    via1_lat = st.number_input("Route 2 Waypoint Lat", value=37.5297, format="%.6f")
    via1_lon = st.number_input("Route 2 Waypoint Lon", value=-121.9189, format="%.6f")

with col4:
    via2_lat = st.number_input("Route 3 Waypoint Lat", value=37.5010, format="%.6f")
    via2_lon = st.number_input("Route 3 Waypoint Lon", value=-122.1312, format="%.6f")

# Efficiency parameters
st.sidebar.subheader("⚡ Efficiency Parameters")
hydrogen_efficiency = st.sidebar.slider(
    "Hydrogen Efficiency (miles per kg)",
    min_value=40, max_value=80, value=60,
    help="Higher values mean better fuel efficiency"
)
elevation_penalty = st.sidebar.slider(
    "Elevation Penalty (meters per extra mile)",
    min_value=10, max_value=50, value=25,
    help="How many meters of elevation gain equals 1 extra mile of distance"
)

# Main analysis function
def analyze_routes(api_key, start, end, via_points, hydrogen_eff=60, elev_penalty=25):
    """Main function to analyze route efficiency"""

    if not api_key:
        st.error("❌ Please configure your OpenRouteService API key")
        st.info("""
        **How to get an API key:**
        1. Visit https://openrouteservice.org/
        2. Sign up for a free account
        3. Get your API key from the dashboard
        4. Add it to Streamlit secrets or enter it manually
        """)
        return None

    try:
        client = openrouteservice.Client(key=api_key)

        # Define routes
        routes_coords = {
            "Route 1 (Direct)": [start, end],
            "Route 2 (Via Fremont)": [start, via_points[0], end],
            "Route 3 (Via Dumbarton)": [start, via_points[1], end]
        }

        all_routes = []

        # Get routes from API
        with st.spinner("🛣️ Fetching route data from OpenRouteService..."):
            for route_name, coords in routes_coords.items():
                try:
                    route = client.directions(
                        coordinates=coords,
                        profile='driving-car',
                        format='geojson',
                        validate=True,
                        instructions=False
                    )
                    geom = LineString(route['features'][0]['geometry']['coordinates'])
                    all_routes.append({'route_id': route_name, 'geometry': geom})
                except Exception as e:
                    st.error(f"Failed to get route {route_name}: {str(e)}")
                    return None

        # Create GeoDataFrame
        gdf = gpd.GeoDataFrame(all_routes, crs='EPSG:4326')

        # Sample points along routes for elevation analysis
        def sample_points(line, spacing_meters=500):
            line_proj = line.to_crs(epsg=3310)
            length = line_proj.geometry.length.values[0]
            distances = np.arange(0, length, spacing_meters)
            sampled_points = [line_proj.geometry.values[0].interpolate(d) for d in distances]
            return gpd.GeoDataFrame(geometry=sampled_points, crs='EPSG:3310').to_crs(epsg=4326)

        all_points = []
        for i, row in gdf.iterrows():
            sampled = sample_points(gdf.loc[[i]])
            sampled['route_id'] = row['route_id']
            all_points.append(sampled)

        points_gdf = gpd.GeoDataFrame(pd.concat(all_points), crs='EPSG:4326')

        # Get elevation data
        def get_elevation_batch(latlons):
            url = 'https://api.open-elevation.com/api/v1/lookup'
            locations = [{"latitude": lat, "longitude": lon} for lat, lon in latlons]
            try:
                response = requests.post(url, json={"locations": locations}, timeout=10)
                response.raise_for_status()
                data = response.json()
                return [pt['elevation'] for pt in data['results']]
            except Exception as e:
                st.warning(f"Elevation API issue: {str(e)}")
                return [np.nan] * len(latlons)

        with st.spinner("⛰️ Fetching elevation data..."):
            latlons = [(pt.y, pt.x) for pt in points_gdf.geometry]
            batch_size = 100
            batches = [latlons[i:i+batch_size] for i in range(0, len(latlons), batch_size)]

            elevations = []
            for i, batch in enumerate(batches):
                elevations += get_elevation_batch(batch)
                # Show progress
                if len(batches) > 1:
                    st.write(f"Progress: {i+1}/{len(batches)} batches")
                time.sleep(0.5)  # Rate limiting

            points_gdf['elevation_m'] = elevations

        # Calculate elevation gain
        elevation_gain = []
        for route in points_gdf['route_id'].unique():
            route_points = points_gdf[points_gdf['route_id'] == route].sort_index()
            diff = route_points['elevation_m'].diff()
            gain = diff[diff > 0].sum()  # only uphill gain
            elevation_gain.append({'route_id': route, 'elevation_gain_m': gain})

        gain_df = pd.DataFrame(elevation_gain)

        # Calculate distances and efficiency
        gdf['distance_miles'] = gdf.to_crs(epsg=3310).geometry.length / 1609.34
        df = gdf[['route_id', 'distance_miles']].merge(gain_df, on='route_id')

        # Compute adjusted effective distance
        df['effective_miles'] = df['distance_miles'] + (df['elevation_gain_m'] / elev_penalty)

        # Hydrogen consumption
        df['hydrogen_kg'] = df['effective_miles'] / hydrogen_eff
        df['hydrogen_per_mile'] = df['hydrogen_kg'] / df['distance_miles']

        # Calculate segment grades for visualization
        def compute_segment_grades(points_df):
            segments = []
            for route in points_df['route_id'].unique():
                points = points_df[points_df['route_id'] == route].reset_index()
                for i in range(len(points) - 1):
                    p1 = points.loc[i].geometry
                    p2 = points.loc[i + 1].geometry
                    line = LineString([p1, p2])

                    # Approximate horizontal distance
                    horiz_dist = p1.distance(p2) * 111_139  # degrees to meters approx

                    # Elevation gain
                    elev_diff = points.loc[i + 1, 'elevation_m'] - points.loc[i, 'elevation_m']

                    # Grade (%)
                    grade = (elev_diff / horiz_dist) * 100 if horiz_dist > 0 else 0

                    segments.append({
                        'geometry': line,
                        'route_id': route,
                        'grade_pct': grade,
                        'elevation_gain': elev_diff
                    })

            return gpd.GeoDataFrame(segments, crs="EPSG:4326")

        segment_gdf = compute_segment_grades(points_gdf)

        return df, gdf, segment_gdf, points_gdf

    except Exception as e:
        st.error(f"❌ Error in route analysis: {str(e)}")
        return None

# Run analysis when button is clicked
if st.sidebar.button("🚀 Analyze Routes", type="primary"):
    start_coord = [start_lon, start_lat]
    end_coord = [end_lon, end_lat]
    via_points = [[via1_lon, via1_lat], [via2_lon, via2_lat]]

    result = analyze_routes(api_key, start_coord, end_coord, via_points,
                           hydrogen_efficiency, elevation_penalty)

    if result:
        df, gdf, segment_gdf, points_gdf = result

        # Display results
        st.header("📊 Route Comparison Results")

        # Metrics in columns
        col1, col2, col3, col4 = st.columns(4)

        best_route = df.loc[df['hydrogen_kg'].idxmin()]

        with col1:
            st.metric(
                "🏆 Most Efficient Route",
                best_route['route_id'],
                delta=f"✅ Saves {df['hydrogen_kg'].max() - best_route['hydrogen_kg']:.2f} kg H₂"
            )

        with col2:
            st.metric(
                "⛽ Best Hydrogen Consumption",
                f"{best_route['hydrogen_kg']:.2f} kg",
                delta=f"📈 {best_route['hydrogen_per_mile']*1000:.1f} g/mile"
            )

        with col3:
            shortest_route = df.loc[df['distance_miles'].idxmin()]
            st.metric(
                "📏 Shortest Distance",
                f"{shortest_route['distance_miles']:.1f} miles",
                delta=shortest_route['route_id']
            )

        with col4:
            min_elev_route = df.loc[df['elevation_gain_m'].idxmin()]
            st.metric(
                "⛰️ Least Elevation Gain",
                f"{min_elev_route['elevation_gain_m']:.0f} m",
                delta=min_elev_route['route_id']
            )

        # Detailed comparison table
        st.subheader("📋 Detailed Route Comparison")

        display_df = df.copy()
        display_df['distance_miles'] = display_df['distance_miles'].round(1)
        display_df['elevation_gain_m'] = display_df['elevation_gain_m'].round(0)
        display_df['effective_miles'] = display_df['effective_miles'].round(1)
        display_df['hydrogen_kg'] = display_df['hydrogen_kg'].round(2)
        display_df['hydrogen_per_mile'] = (display_df['hydrogen_per_mile'] * 1000).round(1)

        display_df = display_df.rename(columns={
            'route_id': 'Route',
            'distance_miles': 'Distance (miles)',
            'elevation_gain_m': 'Elevation Gain (m)',
            'effective_miles': 'Effective Distance (miles)',
            'hydrogen_kg': 'Hydrogen (kg)',
            'hydrogen_per_mile': 'Efficiency (g/mile)'
        })

        # Style the best route
        def highlight_best(row):
            if row['Hydrogen (kg)'] == df['hydrogen_kg'].min():
                return ['background-color: #d4edda'] * len(row)
            else:
                return [''] * len(row)

        st.dataframe(display_df.style.apply(highlight_best, axis=1))

        # Visualization section
        st.header("🗺️ Route Visualization")

        # Create interactive map
        col5, col6 = st.columns([2, 1])

        with col5:
            st.subheader("Route Map with Elevation Grades")

            # Create base map
            center = [points_gdf.geometry.y.mean(), points_gdf.geometry.x.mean()]
            m = folium.Map(location=center, zoom_start=10, tiles='CartoDB positron')

            # Color map for grades
            colormap = cm.linear.RdYlGn_11.scale(
                segment_gdf['grade_pct'].min(),
                segment_gdf['grade_pct'].max()
            )
            colormap = colormap.to_step(n=10)

            # Add segments to map
            route_colors = {'Route 1 (Direct)': 'blue',
                          'Route 2 (Via Fremont)': 'red',
                          'Route 3 (Via Dumbarton)': 'green'}

            for _, row in segment_gdf.iterrows():
                color = colormap(row['grade_pct']) if not np.isnan(row['grade_pct']) else "#999999"
                folium.PolyLine(
                    locations=[(pt[1], pt[0]) for pt in row['geometry'].coords],
                    color=route_colors.get(row['route_id'], color),
                    weight=4,
                    tooltip=f"Route: {row['route_id']}<br>Grade: {row['grade_pct']:.2f}%",
                    opacity=0.8
                ).add_to(m)

            # Add start and end markers
            folium.Marker(
                [start_lat, start_lon],
                popup="Start",
                tooltip="Start",
                icon=folium.Icon(color='green', icon='play')
            ).add_to(m)

            folium.Marker(
                [end_lat, end_lon],
                popup="End",
                tooltip="End",
                icon=folium.Icon(color='red', icon='stop')
            ).add_to(m)

            colormap.caption = "Route Segment Grade (%)"
            colormap.add_to(m)

            folium_static(m, width=700, height=500)

        with col6:
            st.subheader("Route Efficiency")

            # Route efficiency chart
            fig, ax = plt.subplots(figsize=(8, 6))
            routes = df['route_id']
            hydrogen_kg = df['hydrogen_kg']

            colors = ['#1f77b4' if x != min(hydrogen_kg) else '#2ca02c' for x in hydrogen_kg]

            bars = ax.bar(routes, hydrogen_kg, color=colors, alpha=0.7)
            ax.set_ylabel('Hydrogen Consumption (kg)')
            ax.set_title('Hydrogen Efficiency by Route')
            plt.xticks(rotation=45, ha='right')

            # Add value labels on bars
            for bar in bars:
                height = bar.get_height()
                ax.text(bar.get_x() + bar.get_width()/2., height,
                       f'{height:.2f} kg', ha='center', va='bottom')

            st.pyplot(fig)

        # Elevation profile
        st.subheader("⛰️ Elevation Profiles")

        col7, col8, col9 = st.columns(3)

        for i, route in enumerate(points_gdf['route_id'].unique()):
            route_points = points_gdf[points_gdf['route_id'] == route].sort_index()

            fig, ax = plt.subplots(figsize=(10, 4))
            ax.plot(route_points.index, route_points['elevation_m'], linewidth=2, color=['blue', 'red', 'green'][i])
            ax.set_title(f'{route}')
            ax.set_xlabel('Segment')
            ax.set_ylabel('Elevation (m)')
            ax.grid(True, alpha=0.3)
            ax.fill_between(route_points.index, route_points['elevation_m'], alpha=0.3)

            if i == 0:
                with col7:
                    st.pyplot(fig)
            elif i == 1:
                with col8:
                    st.pyplot(fig)
            else:
                with col9:
                    st.pyplot(fig)

        # Download results
        st.subheader("📥 Export Results")

        csv = df.to_csv(index=False)
        st.download_button(
            label="Download Route Analysis CSV",
            data=csv,
            file_name="hydrogen_route_efficiency.csv",
            mime="text/csv"
        )

else:
    # Show instructions when no analysis has been run
    st.info("""
    ## 🚀 Get Started

    1. **🔑 Configure API Key** - Set up your OpenRouteService API key in secrets or enter manually
    2. **📍 Set Route Points** - Adjust start/end locations and waypoints
    3. **⚡ Configure Efficiency** - Set hydrogen efficiency and elevation parameters
    4. **🚀 Analyze Routes** - Click the button to see optimized routes

    ### 💡 Pro Tip
    For production use, add your API key to Streamlit secrets to keep it secure!
    """)

    # Show example of what the dashboard does
    st.header("🎯 How It Works")

    col1, col2, col3 = st.columns(3)

    with col1:
        st.markdown("""
        <div class="metric-card">
            <h3>🛣️ Route Analysis</h3>
            <p>Calculates multiple routes between your chosen points using OpenRouteService API</p>
        </div>
        """, unsafe_allow_html=True)

    with col2:
        st.markdown("""
        <div class="metric-card">
            <h3>⛰️ Elevation Impact</h3>
            <p>Accounts for elevation changes using Open-Elevation API to adjust fuel consumption</p>
        </div>
        """, unsafe_allow_html=True)

    with col3:
        st.markdown("""
        <div class="metric-card">
            <h3>⚡ Efficiency Scoring</h3>
            <p>Ranks routes by hydrogen consumption, distance, and elevation efficiency</p>
        </div>
        """, unsafe_allow_html=True)

# Footer
st.markdown("---")
st.markdown("""
**🔒 Security Note**: API keys are handled securely through Streamlit secrets.
**📊 Data Sources**: Routing from OpenRouteService, elevation data from Open-Elevation API.
**⚠️ Disclaimer**: Route efficiency calculations are estimates based on the provided parameters.
""")